CREATE TABLE course
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    city        VARCHAR(80) NOT NULL,
    duration_in_days    INT NOT NULL,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    price       DOUBLE PRECISION NOT NULL,
    trainer_id  INT NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id),
    CONSTRAINT fk_trainer_id FOREIGN KEY (trainer_id) REFERENCES trainer(id)
);
