server:
  port: 8082

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: course-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/courses/**
        - id: registration-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/registrations/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/jugstalk/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/jugstalk
        registration:
          spring-client:
            provider: keycloak
            client-id: spring-client
            client-secret: vf3bjLCzr2GFgHJ1b7uvcMOEHU0cKzTm
            authorization-grant-type: authorization_code
            scope: openid

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE